from datetime import date
import zipfile
from io import BytesIO
from xml.etree import ElementTree

from app.excel.exporter import SHEETS, build_workbook
from app.services.finance import KPIResult


def test_excel_sheets_present():
    kpis = [
        KPIResult(
            period=date(2024, 1, 1),
            revenue=100,
            gross_profit=60,
            gross_margin=0.6,
            opex=40,
            ebitda=20,
            burn=0,
            cash_balance=1000,
            runway_months=12,
        )
    ]
    data = build_workbook(
        "TestCo",
        kpis,
        kpis,
        [{"name": "Base"}],
        [{"name": "Base", "ending_revenue": 100, "ending_ebitda": 20, "ending_runway_months": 12}],
        [{"name": "Upside", "delta_revenue": 10, "delta_ebitda": 5, "delta_runway_months": 1}],
        [{"runway_months": 12}],
    )
    assert data
    with zipfile.ZipFile(BytesIO(data)) as workbook:
        xml = workbook.read("xl/workbook.xml")
    root = ElementTree.fromstring(xml)
    sheets = [sheet.attrib["name"] for sheet in root.findall(".//{http://schemas.openxmlformats.org/spreadsheetml/2006/main}sheet")]
    for sheet in SHEETS:
        assert sheet in sheets


def test_excel_contains_expected_strings():
    kpis = [
        KPIResult(
            period=date(2024, 1, 1),
            revenue=100,
            gross_profit=60,
            gross_margin=0.6,
            opex=40,
            ebitda=20,
            burn=0,
            cash_balance=1000,
            runway_months=12,
        )
    ]
    data = build_workbook(
        "TestCo",
        kpis,
        kpis,
        [{"name": "Base", "revenue_growth": 0.05, "gross_margin": 0.6, "opex_growth": 0.03}],
        [{"name": "Base", "ending_revenue": 120, "ending_ebitda": 25, "ending_runway_months": 12}],
        [{"name": "Upside", "delta_revenue": 10, "delta_ebitda": 5, "delta_runway_months": 1}],
        [{"revenue_growth": 0.05, "gross_margin": 0.6, "runway_months": 12}],
    )
    with zipfile.ZipFile(BytesIO(data)) as workbook:
        shared_strings = workbook.read("xl/sharedStrings.xml").decode("utf-8")
    assert "TestCo" in shared_strings
    assert "Generated by Portfolio Reporting Studio" in shared_strings
    assert "ending_runway_months" in shared_strings
