from io import BytesIO

import pandas as pd
import xlsxwriter

from app.services.finance import KPIResult


SHEETS = [
    "Summary",
    "P&L Actuals",
    "KPI Trends",
    "Forecast",
    "Scenarios",
    "Scenario Comparison",
    "Scenario Deltas",
    "Sensitivity",
    "Notes",
]


def build_workbook(
    company_name: str,
    kpis: list[KPIResult],
    forecast: list[KPIResult],
    scenarios: list[dict[str, float]],
    scenario_results: list[dict[str, float]],
    scenario_deltas: list[dict[str, float]],
    sensitivity: list[dict[str, float]],
) -> bytes:
    output = BytesIO()
    workbook = xlsxwriter.Workbook(output, {"in_memory": True})

    summary = workbook.add_worksheet("Summary")
    summary.write("A1", "Company")
    summary.write("B1", company_name)
    summary.write("A2", "Latest Revenue")
    summary.write("B2", kpis[-1].revenue if kpis else 0)
    summary.write("A3", "Latest Runway (months)")
    summary.write("B3", kpis[-1].runway_months if kpis else 0)

    pnl_ws = workbook.add_worksheet("P&L Actuals")
    pnl_df = pd.DataFrame([k.__dict__ for k in kpis])
    _write_df(pnl_ws, pnl_df)

    kpi_ws = workbook.add_worksheet("KPI Trends")
    _write_df(kpi_ws, pnl_df[["period", "revenue", "gross_margin", "ebitda", "runway_months"]])

    forecast_ws = workbook.add_worksheet("Forecast")
    forecast_df = pd.DataFrame([k.__dict__ for k in forecast])
    _write_df(forecast_ws, forecast_df)

    scenarios_ws = workbook.add_worksheet("Scenarios")
    scenarios_df = pd.DataFrame(scenarios)
    _write_df(scenarios_ws, scenarios_df)

    scenario_results_ws = workbook.add_worksheet("Scenario Comparison")
    scenario_results_df = pd.DataFrame(scenario_results)
    _write_df(scenario_results_ws, scenario_results_df)

    scenario_deltas_ws = workbook.add_worksheet("Scenario Deltas")
    scenario_deltas_df = pd.DataFrame(scenario_deltas)
    _write_df(scenario_deltas_ws, scenario_deltas_df)

    sensitivity_ws = workbook.add_worksheet("Sensitivity")
    sensitivity_df = pd.DataFrame(sensitivity)
    _write_df(sensitivity_ws, sensitivity_df)

    notes_ws = workbook.add_worksheet("Notes")
    notes_ws.write("A1", "Generated by Portfolio Reporting Studio")

    workbook.close()
    return output.getvalue()


def _write_df(worksheet, df: pd.DataFrame) -> None:
    if df.empty:
        return
    for col_idx, col in enumerate(df.columns):
        worksheet.write(0, col_idx, col)
    for row_idx, row in enumerate(df.itertuples(index=False), start=1):
        for col_idx, value in enumerate(row):
            worksheet.write(row_idx, col_idx, value)
